### PR TITLE
Add suterusu to the list

### PR DESCRIPTION
**Pull request by suterusu-io**
Suterusu is building a general-purpose layer-2 privacy protocol with their own zk-ConSNARK, a derivative from zk-SNARK doesn't require trusted setup.  Design can be found from https://github.com/suterusu-team/Suter_yellowpaper.

### CODE REVIEW

**Comment by gluk64** [comment]
Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.

**Comment by HLin2014** [comment]
Hey, if you have any concrete arguments to support your opinion, you are welcome to leave your comments. Otherwise, please avoid leaving any type of void conclusion like this. No one would take your opinion seriously if you behave in this manner. BTW, there are thousands of reasons to believe the zk-rollup you are currently working on is a scam too. 

> Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.

Hey, if you have any concrete arguments to support your opinion, you are welcome to leave your comments. Otherwise, please avoid leaving any type of void conclusion like this. No one would take your opinion seriously if you behave in this manner. BTW, there are thousands of reasons to believe the zk-rollup you are currently working on is a scam too.

**Comment by HLin2014** [comment]
> Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.

Hey, if you have any concrete arguments to support your opinion, you are welcome to leave your comments. Otherwise, please avoid leaving any type of void conclusion like this. No one would take your opinion seriously if you behave in this manner.

**Comment by gluk64** [comment]
If the authors claim to have invented a new SNARK construction, please link me to a publication on https://eprint.iacr.org/ or any other well respected peer-reviewed cryptogrpahy medium.

**Comment by HLin2014** [comment]
Our constant-size range proof scheme is described in the yellowpaper, which is publicly available in the Github. FYI, eprint is not a peer-reviewed crypto medium. It's just another public repo, same as Github.

**Comment by HLin2014** [comment]
Since we are talking about scam, I have a few questions regarding zk-rollup too. Since zk-rollup requires an operator to help with the proof generation, what would happen if this operator is DOS attacked? The marketing of zk-rollup seems to give the impression that you could build dex based on zk-rollup. What if the operator colludes with the miner and launches a front-running attack? Wouldn't it make the front-running attack a lot easier since now the miner controls not only the transaction verification process but also the transaction generation process?

**Comment by swasilyev** [comment]
> Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.

I had the same thought. And i really enjoy how @HLin2014 is overreacting.

**Comment by suterusu-io** [comment]
> > Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.
> 
> I had the same thought. And i really enjoy how @HLin2014 is overreacting.

In which way, it gives you such impression? 
How about those concerns with zk-rollup raised by @HLin2014

**Comment by HLin2014** [comment]
> > Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.
> 
> I had the same thought. And i really enjoy how @HLin2014 is overreacting.

Nice trolling, dude. Seriously, it would be nice to hear some quality response from the zk-rollup community on why the attacks mentioned in my response are not a concern and zk-rollup is not a scam.

**Comment by swasilyev** [comment]
> > Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.

> In which way, it gives you such impression?
Sorry, i'm not from your marketing team.
> How about those concerns with zk-rollup raised by @HLin2014
Absolutely irrelevant here. This github is "A _curated_ list of **awesome** things related to learning zero knowledge proofs", if you haven't noticed

**Comment by HLin2014** [comment]
> > > Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.
> 
> > In which way, it gives you such impression?
> 
> Sorry, i'm not from your marketing team.
> 
> > How about those concerns with zk-rollup raised by @HLin2014
> 
> Absolutely irrelevant here. This github is "A _curated_ list of **awesome** things related to learning zero knowledge proofs", if you haven't noticed

I don't understand. So zk-rollup is not related to zkp or it's not awesome?

**Comment by suterusu-io** [comment]
> > > Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.
> 
> > In which way, it gives you such impression?
> > Sorry, i'm not from your marketing team.
Let me be straight, if you make a accusation, you should have evidence to support it. Otherwise, it Is illegitimate. 
> > How about those concerns with zk-rollup raised by @HLin2014
> > Absolutely irrelevant here. This github is "A _curated_ list of **awesome** things related to learning zero knowledge proofs", if you haven't noticed

**Comment by gluk64** [comment]
The yellow paper mentions "the academic version of this work". Looking forward to it.

**Comment by HLin2014** [comment]
> > > Checked the paper and the github, this doesn't look serious to me. Strongly resembling a typical ICO scam.
> 
> > In which way, it gives you such impression?
> 
> Sorry, i'm not from your marketing team.
> 
> > How about those concerns with zk-rollup raised by @HLin2014
> 
> Absolutely irrelevant here. This github is "A _curated_ list of **awesome** things related to learning zero knowledge proofs", if you haven't noticed

Stop evading the question, or you give people a solid reason to call zk-rollup a scam.

**Comment by HLin2014** [comment]
> The yellow paper mentions "the academic version of this work". Looking forward to it.

Thanks.

**Pull request closed without merging**
